routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('blog/{slug}', ['as' => 'blog.single', 'uses'=> 'BlogController@getSingle'])
->where('slug', '[\w\d\-\_]+');

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::get('about', 'PagesController@getAbout'); 

Route::get('/', 'PagesController@getIndex');

Route::get('create', 'PagesController@getPost');

Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index' ]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');

//Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);

//Tags
Route::resource('tags', 'TagController', ['except'=>['create']]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::post('comments/{post_d}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);

Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);

Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);

Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);

Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    public function Posts()
    {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, array(
            'name' => 'required|max:255'));

            $tag = new Tag;
            $tag->name = $request->name;

            $tag->save();

            Session::flash('success', 'New Tag Successfully created');

            return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $tag = Tag::find($id);
        return view('tags.show')->withTag($tag);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $tag =  Tag::find($id);
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $tag = Tag::find($id);
        $this->validate($request, ['name' => 'required|max:255']);

        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'Tag successfully saved');
        return redirect()->route('tags.show', $tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $tag = Tag::find($id);
        $tag->posts()->detach();
        $tag->delete();

        Session::flash('success', 'Tag deleted!!');

        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('main')

@section('title', '| Edit Tag ')

@section('content')

<div class="col-md-12" style="margin-top:80px">

{{ Form::model($tag, ['route'=>['tags.update', $tag->id], 'method' => "PUT"]) }}

{{Form::label('name', 'Title')}}
{{Form::text('name',null,['class' => 'form-control'])}}
{{Form::submit('Save Changes', ['class'=>'btn btn-info form-spacing-top'])}}
{{Form::close()}}

</div>

@endsection()

resources/views/tags/index.blade.php
@extends ('main')

@section('title', '| All Tags')

@section('content')

<div style="margin-top:80px" class="row">
    <div class="col-md-8 mx-auto">
        <h1>Tags</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                </tr>
            </thead>

            <tbody>
                @foreach($tags as $tag)
                <tr>
                    <th>{{ $tag->id }}</th>
                    <th><a href="{{ route('tags.show', $tag->id) }}"> {{ $tag->name }} </a></th>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="col-md-3">
        <div class="category-well">

            {!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}

            <h2>New Tag</h2>
            {{ Form::label('name', 'Name:' ) }}
            {{ Form::text('name', null, ['class' => 'form-control']) }}

            {{ Form::submit('Create New Tag', ['class'=>'form-spacing-top btn btn-block btn-info']) }}

            {!! fORM::close() !!}

        </div>
    </div>

</div>


@stop()

resources/views/tags/show.blade.php
@extends ('main')

@section('title', "| $tag->name Tag")

@section('content')

<div class="row" style="margin-top:80px">

<div class="col-md-8">
    <h1>  {{ $tag->name }} Tag <small style="font-size:20px">( {{$tag->posts()->count()}} Posts)</small> </h1>
</div>

<div class="col-md-2">
<a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info pull-right">Edit</a>
</div>

<div class="col-md-2">
{{ Form::open(['route' => ['tags.destroy', $tag->id], 'method'=>'DELETE']) }}
{{ Form::submit('Delete', ['class' => 'btn btn-danger'])}}
</div>


</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Tags</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach($tag->posts as $post)
                <tr>
                <th>{{$post->id}}</th>
                <td>{{$post->title}}</td>
                <td> @foreach($post->tags as $tag)
                <span class="badge badge-info"> {{ $tag->name }} </span>
                @endforeach
                </td>

                    <td><a href="{{ route('post.show', $post->id)}}" class="btn btn-sm btn-success">View</a>

                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@stop()