routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('blog/{slug}', ['as' => 'blog.single', 'uses'=> 'BlogController@getSingle'])
->where('slug', '[\w\d\-\_]+');

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::get('about', 'PagesController@getAbout'); 

Route::get('/', 'PagesController@getIndex');

Route::get('create', 'PagesController@getPost');

Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index' ]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');

//Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);

//Tags
Route::resource('tags', 'TagController', ['except'=>['create']]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::post('comments/{post_d}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);

Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);

Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);

Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);

Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

resources/views/partials/_css.blade.php
<!--Minified CSS-->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">   
       <link rel="stylesheet" href="css/parsley.css">
       
    
    

resources/views/partials/_footer.blade.php
<hr>
<p style="text-align:center">Copyright Ireri Mwenda. All rights reserved 2019</p>
                

resources/views/partials/_head.blade.php
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel Blog @yield('title')</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">

        <!--Custom CSS-->
        {{Html::style('css/style.css')}}

        {{Html::style('css/select2.min.css')}}

      
      

resources/views/partials/_javascript.blade.php
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="js/parsley.js"></script>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))


<div class="alert alert-secondary" role="alert">
  <strong>Success</strong> {{ Session::get('success') }}
</div>

@endif

@if(count($errors) > 0)

  <div class="alert alert-danger" role="alert">
  <strong>Errors:</strong>

  <ul>
  @foreach($errors->all() as $error)
  <li>{{ $error}}</li>
  @endforeach
  </ul>

  </div>

@endif

resources/views/partials/_navs.blade.php
<div class="flex-center position-ref full-height">
           
                <div class="top-right links">
                
                <a href="/blog">Blog</a>
               

                @if (Auth::check())
                 <a href="/home">Home</a>

                <a href="{{route('post.index')}}">Posts</a>

                <a href="{{route('categories.index')}}">Categories</a>
          
                <a href="{{route('tags.index')}}">Tags</a>

                <a href="{{route('logout')}}">Logout</a>

                 @else

                 <a href="{{route('login')}}">Login</a>

                <a href="{{ route('register') }}">Register</a>

                 @endif
                </div>
           


            