routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('blog/{slug}', ['as' => 'blog.single', 'uses'=> 'BlogController@getSingle'])
->where('slug', '[\w\d\-\_]+');

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::get('about', 'PagesController@getAbout'); 

Route::get('/', 'PagesController@getIndex');

Route::get('create', 'PagesController@getPost');

Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index' ]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');

//Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);

//Tags
Route::resource('tags', 'TagController', ['except'=>['create']]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::post('comments/{post_d}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);

Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);

Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);

Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);

Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function tags()
        {
            return $this->belongsToMany('App\Tag');
        }

        public function comments()
        {
            return $this->hasMany('App\Comment');
        }
    
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Session;
use App\Category;
use App\Tag;
use Image;
use Storage;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Create variable and store in fromDB
        $posts = Post::orderBy('created_at', 'desc') -> paginate(5);

        //Return view and pass variable
        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all(); 
        return view('posts.create')->withCategories($categories)->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        //Validate
        $this->validate($request, array(
            'title' => 'required|max:150',
            'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'category_id' => 'required|integer',
            'body' => 'required',
            'featured_image' => 'sometimes|image'
        ));

        //Store in DB
        $post = new Post;
        
        $post->title = $request->title;
        $post->slug= $request->slug;
        $post->category_id = $request->category_id;
        $post->body = $request->body;

         //Save image
         if($request->hasFile('featured_image'))
         {
             $image = $request->file('featured_image');
             $filename = time() . '.' . $image->getClientOriginalExtension();
             $location = public_path('images/' . $filename);
             $image = Image::make($image)->resize(800,400)->save($location);
 
             $post->image = $filename;
         }

        $post->save();

        $post->tags()->sync($request->tags, false);

        Session::flash('success', 'Blog post successfully posted');

        //Redirect
        return redirect()->route('post.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show')->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //  Find Post in DB and save as a variable
        $post = Post::find($id);
        $categories = Category::all();
        $cats = array();
        foreach($categories as $category){
            $cats[$category->id] = $category->name;
        }

        $tags=Tag::all();
        $tags2=array();
        foreach($tags as $tag)
        {
            $tags2[$tag->id] = $tag->name;
        }

        //  Return the view and pass in the previously created variable
        return view('posts.edit')->withPost($post)->withCategories($cats)->withTags($tags2);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //  Validate Data
        $post=Post::find($id);

       // if($request->input('slug') == $post->slug){
          //  $this->validate($request, array(
            //    'title' => 'required|max:150',
              //  'category_id' => 'required|integer',
              //  'body' => 'required'
            //));
     // }else{
            $this->validate($request, array(
                'title' => 'required|max:150',
                'slug' => "required|alpha_dash|min:5|max:200|unique:posts,slug,$id",
                'category_id' => 'required|integer',
                'body' => 'required',
                'featured_image' => 'image'
            ));
       // }

        //  Save Data to DB
        $post = Post::find($id);
        
        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->category_id = $request->input('category_id');
        $post->body = $request->input('body');

        if($request->hasFile('featured_image'))
        {
            //Add new photo
            $image = $request->file('featured_image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            $image = Image::make($image)->resize(800,400)->save($location);
                
            $oldfilename = $post->image;

            //Update DB

            $post->image = $filename;

            //dELETE OLD PHOTO

            Storage::delete($oldfilename);
        }

        $post->save();

        if(isset($request->tags)){

        $post->tags()->sync($request->tags, true);

    }else{
        $post->tags()->sync(array());
    }
        //  Set Flash data with success message
        Session::flash('success', 'Post successfully updated!');

        //  Redirect with Flash data to show request
        return redirect()->route('post.show', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE FROM DB
        $post = Post::find($id);
        $post->tags()->detach();
        Storage::delete($post->image);
        $post->delete();

        Session::flash('success', 'Post successfully deleted');
        return redirect()->route('post.index');
    }
}

resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create New Post')

@include('partials._css')

@section('stylesheets')
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>


<script>
tinymce.init({
  selector: 'textarea'
});
</script>

@endsection()

@section('content')

<div class="create-post row">
    <div class="col-md-8 col-md-offset-2 mx-auto">
        
        <h1>Create New Post</h1>
        <hr>
        
        {!! Form::open(['route' => 'post.store', 'data-parsley-validate' =>'', 'files'=>true]) !!}
          {{ Form::label('title', 'Title:', ['style'=>'font-weight:bold']) }}
          {{ Form::text('title',null,array('class' => 'form-control', 'required' => '','maxlength' => '200'))}}

           {{ Form::label('slug', 'Slug:', ['style'=>'font-weight:bold'])}}
           {{ Form::text('slug',null,array('class'=>'form-control', 'required' => '', 'minlength'=>'5', 'maxlength'=>'255'))}}

          {{ Form::label('category_id', 'Category', ['style'=>'font-weight:bold'])}}
          <select class="form-control" name="category_id">
          
          @foreach($categories as $category)
            <option value='{{$category->id}}'>{{$category->name}}</option>
            @endforeach

          </select><br>

          {{ Form::label('tags', 'Tags:', ['style'=>'font-weight:bold'])}}
          <select class="form-control select2-multi" name="tags[]" multiple="multiple">
          
          @foreach($tags as $tag)
            <option value='{{$tag->id}}'>{{$tag->name}}</option>
            @endforeach

          </select><br><br>

          {{Form::label('featured_image', 'Upload featured image')}}
          {{Form::file('featured_image')}}
<br>
          {{ Form::label('body', "Post Body:", ['style'=>'font-weight:bold'])}}
          {{ Form::textarea('body', null,array('class'=>'form-control'))}}
        
          {{ Form::submit('Create Post',array('class'=>'btn btn-info btn-lg', 'style'=>'margin-top:20px;'))}}
        {!! Form::close() !!}

    </div>
</div>

@include('partials._javascript')

@stop()

@section('scripts')

  {!! Html::script('js/select2.min.js') !!}

  <script type="text/javascript">
  $('.select2-multi').select2();
  </script>

@endsection()

resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')


@section('stylesheets')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

<script>
tinymce.init({
  selector: 'textarea'
});
</script>

@endsection()

@include('partials._css')

@section('content')

<div style="margin-top:80px" class="row">


<div class="edit-section col-md-7">

{!! Form::model($post, ['route' => ['post.update', $post->id], 'method'=>'PUT', 'files' => true]) !!}

{{ Form::label('title', 'Title:')}}
{{ Form::text('title', null, ["class" => 'form-control input-lg']) }}

{{ Form::label('slug', 'Slug:', ['class'=> 'form-spacing-top'])}}
{{Form::text('slug',null,["class" => 'form-control'])}}

{{Form::label('category_id', 'Category:', ['class' => 'form-spacing-top'])}}
{{Form::select('category_id', $categories, null, ['class' => 'form-control'])}}

{{Form::label('tags', 'Tags:', ['class' => 'form-spacing-top'])}}
{{Form::select('tags[]', $tags, null, ['class'=>'form-control select2-multi', 'multiple'=>'multiple'])}}
<br><br>
{{Form::label('featured_image', 'Update featured image')}}
{{Form::file('featured_image')}}
<br>
{{ Form::label('body', "Body:", ['class' => 'form-spacing-top']) }}
{{ Form::textarea('body', null, ["class" => 'form-control']) }}

</div>

<div class="col-md-4">
    <div class="well">

    <dl class="dl-horizantal">
        <dt>Created At</dt>
        <dd>{{date('M j, Y h:i a', strtotime($post->created_at))}}</dd>
    </dl>

    <dl class="dl-horizantal">
            <dt>Last Updated At</dt>
            <dd>{{date('M j, Y h:i a', strtotime($post->updated_at))}}</dd>
        </dl>

        <hr>

        <div class="row">
            <div class="col-sm-6">
                    {!! Html::linkRoute('post.show', 'Cancel', array($post->id), array('class' => 'btn btn-danger')) !!}
            </div>

            <div class="col-sm-6">
                    {{ Form::submit('Save Changes', ['class' => 'btn btn-success']) }}
            </div>
        </div>
    
    </div>

</div>

{!! Form::close() !!}

</div>

@include('partials._javascript')

@stop()

@section('scripts')

  {!! Html::script('js/select2.min.js') !!}

  <script type="text/javascript">
  $('.select2-multi').select2();
  $('.select2-multi').select2().val({!! json_encode($post->tags()->allRelatedIds())
   !!}).trigger('change');

  </script>

@endsection()

resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Posts')

@section('content')


<div style="margin-top:80px" class="row">
    <div class="col-md-10">
        <h1>All Posts</h1>
    </div>

<div class="col-md-2">
    <a href="  {{route('post.create')}} " class="btn btn-info">Create New Post</a>
</div>

<div class="col-md-12">
    <hr>
</div>

</div>


<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <th>#</th>
                <th>Title</th>
                <th>Body</th>
                <th>Created At</th>
                <th></th>
            </thead>

            <tbody>
                
                @foreach($posts as $post)

                <tr>
                    <th>{{ $post->id }}</th>
                    <td>{{ $post->title }}</td>
                    <td>{{ substr($post->body, 0, 60) }} {{ strlen($post->body)>50 ? "..." : "" }} </td>
                    <td>{{ date('M j, Y',strtotime($post->created_at)) }}</td>
                    <td>
                        <a href="{{route('post.show', $post->id)}}" class="btn btn-info">View</a>
                        <a href="{{route('post.edit', $post->id)}}" class="btn btn-warning">Edit</a>
                </td>
                </tr>

                @endforeach

            </tbody>
        </table>

<div class="text-center">
    {!! $posts->render(); !!}
</div>

    </div>
</div>


@stop()

resources/views/posts/show.blade.php
@extends('main')

@section('title', '|View Post')


@section('content')


<div style="margin-top:80px" class="row">


<div class="col-md-8">

<img style="width:250px;height:250px" src="{{asset('images/'.$post->image)}}" />

<h1>{{ $post->title }}</h1>
<p class="lead">{{ $post->body }}</p>

<hr>
@foreach ($post->tags as $tag)

    <span class="badge badge-info"> {{$tag->name}} </span>

@endforeach

</div>

<div id="backend-comments" style="margin-top:50px">
<h3>Comment <small> {{ $post->comments()->count() }} total</small></h3>

<table class="comment-table table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Comment</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($post->comments as $comment)
        <tr>
            <td> {{ $comment->name }} </td>
            <td> {{$comment->email}} </td>
            <td> {{$comment->comment}} </td>
            <td>
            <a href="{{ route('comments.edit', $comment->id)}}" class="btn btn-info">Edit</a>
            <a href="{{ route('comments.delete', $comment->id)}}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
</div>

<div class="col-md-4">
    <div class="well">

    <dl class="dl-horizantal">
        <dt>Url:</dt>
        <dd><a href="{{ url('blog/'.$post->slug) }}">{{ url('blog/'.$post->slug) }}</a></dd>
    </dl>

     <dl class="dl-horizantal">
        <dt>Category: </dt>
        <dd><p> {{ $post->category->name }} </p></dd>
    </dl>

    <dl class="dl-horizantal">
        <dt>Created At</dt>
        <dd>{{date('M j, Y h:i a', strtotime($post->created_at))}}</dd>
    </dl>

    <dl class="dl-horizantal">
            <dt>Updated At</dt>
            <dd>{{date('M j, Y h:i a', strtotime($post->updated_at))}}</dd>
        </dl>

        <hr>

        <div class="row">
            <div class="col-sm-6">
                    {!! Html::linkRoute('post.edit', 'Edit', array($post->id), array('class' => 'btn btn-lg btn-info')) !!}
            </div>

            <div class="col-sm-6">
                {!! Form::open(['route' => ['post.destroy', $post->id], 'method'=>'DELETE']) !!}

                {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}

                {!! Form::close() !!}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                {{ Html::linkRoute('post.index', '<< See All Posts', [], ['class' => 'btn  btn-warning']) }}
            </div>
        </div>
       

</div>
</div>

</div>



@stop()